spring:
  profiles:
    active:
      on-profile: local
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_SCHEMA}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none #create, create-drop, none, update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # set DB column name by snake case
    show-sql: true
    generate-ddl: true
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER # Swagger-ui
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  ### DB initialize auto insert ###
  sql:
    init:
      mode: always
      encoding: utf-8
      # data-locations: "classpath: data.sql" #use different file for initializing data
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
  config: classpath:logback.xml
jwt:
  secret: ${JWT_TOKEN_SECRET_KEY}
sns:
  kakao:
    key: ${KAKAO_API_KEY}
    url: ${KAKAO_REDIRECT_URL}
sms:
  key: ${SMS_API_KEY}
  secret: ${SMS_API_SECRET_KEY}
  phoneNumber: ${PHONE_NUMBER}
mail:
  id: ${NAVER_ID}
  password: ${NAVER_PASSWORD}

sentry:
  dsn: ${SENTRY_DSN}
  log:
    level : ERROR
  traces-sample-rate: 1.0

amazon:
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT}
    region: ${DYNAMODB_REGION}
  aws:
    accessKey: ${DYNAMODB_ACCESS_KEY}
    secretKey: ${DYNAMODB_SECRET_KEY}